### ISSUE TITLE
Chatops integration isn't working with spaces in commands.

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/hubot-stackstorm#37]
Problem:

!ansible uname -> WORKS
!ansible "uname -a" -> doesn't work.
!ansible 'uname -a' -> doesn't work. 

Specs:

bacon [4:12 PM] 
st2 ('0.13.2.5',)
st2 client 0.13.2.5
prd.testing.lanets.ca 3.13.0-32-generic
Python 2.7.6

bacon [4:12 PM]
I could update python to 2.7.9.

bacon [4:13 PM] 
hubot-stackstorm@0.2.3

**Comment by LaurentDumont** [comment]
For reference, I had been using the Stackstorm/Chat-Ops guide http://stackstorm.com/2015/06/24/ansible-chatops-get-started-%F0%9F%9A%80/

**Comment by armab** [comment]
Thanks @LaurentDumont for report, I can confirm it:
http://i.imgur.com/HirRzDV.png

Also the message doesn't reach st2 api, should be some filtering on `hubot-stackstorm` plugin side.

**Comment by armab** [comment]
Another report via #community from **bryantebeek** about using spaces in chatops commands:

```yaml
formats:
  - "slack say {{text}} in {{channel}}"
```
Using `!slack say foo bar in chatops` doesn't work. Same for `!slack say "foo bar" in chatops` or `!slack say 'foo bar' in chatops`

So this bug applies for any chatops command with spaces, @lakshmi-kannan can you change the title then, since it's unrelated to ansible?
Should be regression in some version, because spaces worked before.

**Comment by manasdk** [comment]
Fixed https://github.com/StackStorm/hubot-stackstorm/pull/42

**Comment by bryantebeek** [comment]
@manasdk Upgraded to 0.2.5 but still not working on my side.
